[phases.setup]
nixPkgs = ["python311", "gcc", "pkg-config", "openssl"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn app:app --host 0.0.0.0 --port $PORT"

[variables]
PORT = "8080"